# -*- coding: utf-8 -*-
"""Customer_Churn_and_Retention_Strategy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dtCMux4UjltpKYTvPur7a0491wLrru4X

# Customer Churn & Retention Strategy
### End-to-End Pipeline: Feature Engineering → Modeling → SHAP → Segmentation → CLV → Revenue-at-Risk → Retention Prioritization → Budget/ROI

**Status coming into this notebook:** data gathering, understanding, cleaning and core EDA are already complete (see the project context report). This notebook picks up from **feature selection** and runs the pipeline through to **business recommendations**.

**How to use this notebook:** run the cells top to bottom, in order. Each section has a markdown cell explaining *what* the step does and *why*, followed by the code. Read the printed output after each code cell before moving to the next — that's your evidence for what the model actually learned, and it's also your answer bank for interview questions about this project.

## 0. Setup: Mount Drive, Import Libraries, Define Paths

This mirrors the folder structure agreed in the project context report. Nothing here overwrites `data/raw/`.
"""



# --- Mount Google Drive ---
from google.colab import drive
drive.mount('/content/drive')

# --- Install any missing packages (Colab usually has these already) ---
!pip install -q xgboost shap

# --- Core imports ---
import os
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    roc_auc_score, roc_curve, precision_recall_curve,
    classification_report, confusion_matrix, f1_score,
    precision_score, recall_score, ConfusionMatrixDisplay
)
from xgboost import XGBClassifier
import shap
import joblib

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
sns.set_style("whitegrid")

print("Libraries loaded.")

# --- Project paths (matches the agreed Drive structure) ---
ROOT = "/content/drive/MyDrive/Colab Notebooks/Customer_Churn_&_Retention_Strategy/"

RAW_PATH       = ROOT + "data/raw/"
PROCESSED_PATH = ROOT + "data/processed/"
EXTERNAL_PATH  = ROOT + "data/external/"
MODELS_PATH    = ROOT + "models/"
FIGURES_PATH   = ROOT + "outputs/figures/"
TABLES_PATH    = ROOT + "outputs/tables/"

for p in [PROCESSED_PATH, EXTERNAL_PATH, MODELS_PATH, FIGURES_PATH, TABLES_PATH]:
    os.makedirs(p, exist_ok=True)

print("Paths ready.")

"""## 1. Load Data & Reproduce Cleaning

If you already saved a cleaned file from your earlier EDA notebook to `data/processed/`, this cell will use it directly. Otherwise it reloads the raw CSV and reproduces the exact cleaning steps already validated in your EDA (the 11 blank `TotalCharges` rows — all tenure = 0, Churn = No — are set to 0.0, matching the report's finding).

"""

import subprocess
result = subprocess.run(
    ['find', '/content/drive/MyDrive', '-iname', '*churn*'],
    capture_output=True, text=True
)
print(result.stdout)

processed_file = PROCESSED_PATH + "telco_churn_cleaned.csv"
raw_file = RAW_PATH + "WA_Fn-UseC_-Telco-Customer-Churn.csv"  # adjust filename if different

if os.path.exists(processed_file):
    df = pd.read_csv(processed_file)
    print(f"Loaded already-cleaned data: {df.shape}")
else:
    df = pd.read_csv(raw_file)
    print(f"Loaded raw data: {df.shape}")

    # Reproduce cleaning steps from the EDA phase
    df['TotalCharges'] = df['TotalCharges'].replace(' ', np.nan)
    df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
    df['TotalCharges'] = df['TotalCharges'].fillna(0.0)  # all 11 blanks had tenure=0, Churn=No

    assert df['TotalCharges'].isna().sum() == 0
    assert df.duplicated(subset='customerID').sum() == 0

    df.to_csv(processed_file, index=False)
    print(f"Cleaned data saved to: {processed_file}")

df.head()

"""## 2. Feature Selection & Engineering

**Feature selection decisions:**
- `customerID` is dropped from modeling (identifier, no predictive signal) but kept aside for later customer-level outputs (risk scores, segments).
- `Churn` is mapped to binary (`Yes` → 1, `No` → 0) and separated as the target.
- All other original columns are retained as candidate features — the encoding step (Section 3) will handle categoricals.

**Engineered features (15):** built directly from the EDA findings in the report — e.g. contract risk, payment friction, service-gap signals, and tenure/charge interactions.

"""

# Keep customerID aside; encode target
customer_ids = df['customerID'].copy()
df['Churn_binary'] = df['Churn'].map({'Yes': 1, 'No': 0})

# Guard against tenure=0 division issues
safe_tenure = df['tenure'].replace(0, 1)

# --- 15 engineered features ---
df['tenure_group'] = pd.cut(df['tenure'], bins=[-1, 12, 24, 48, 72],
                             labels=['0-12', '13-24', '25-48', '49-72'])                       # 1
df['is_new_customer'] = (df['tenure'] <= 12).astype(int)                                       # 2

addon_cols = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
              'TechSupport', 'StreamingTV', 'StreamingMovies']
df['num_addon_services'] = (df[addon_cols] == 'Yes').sum(axis=1)                               # 3

df['has_internet'] = (df['InternetService'] != 'No').astype(int)                               # 4
df['avg_monthly_spend'] = df['TotalCharges'] / safe_tenure                                     # 5

df['monthly_charge_bucket'] = pd.qcut(df['MonthlyCharges'], 4,
                                       labels=['Low', 'Medium-Low', 'Medium-High', 'High'])     # 6
df['total_charge_bucket'] = pd.qcut(df['TotalCharges'].rank(method='first'), 4,
                                     labels=['Low', 'Medium-Low', 'Medium-High', 'High'])       # 7

df['is_month_to_month'] = (df['Contract'] == 'Month-to-month').astype(int)                     # 8
df['is_electronic_check'] = (df['PaymentMethod'] == 'Electronic check').astype(int)             # 9
df['is_fiber_optic'] = (df['InternetService'] == 'Fiber optic').astype(int)                    # 10

df['num_dependents_partner'] = ((df['Partner'] == 'Yes').astype(int) +
                                 (df['Dependents'] == 'Yes').astype(int))                       # 11

df['paperless_and_echeck'] = ((df['PaperlessBilling'] == 'Yes') &
                               (df['PaymentMethod'] == 'Electronic check')).astype(int)         # 12  (high-risk combo)

df['tenure_to_charge_ratio'] = safe_tenure / (df['MonthlyCharges'] + 1)                         # 13

df['is_senior_alone'] = ((df['SeniorCitizen'] == 1) &
                          (df['Partner'] == 'No') &
                          (df['Dependents'] == 'No')).astype(int)                               # 14

df['service_to_charge_ratio'] = df['num_addon_services'] / (df['MonthlyCharges'] + 1)           # 15

engineered_features = [
    'tenure_group', 'is_new_customer', 'num_addon_services', 'has_internet',
    'avg_monthly_spend', 'monthly_charge_bucket', 'total_charge_bucket',
    'is_month_to_month', 'is_electronic_check', 'is_fiber_optic',
    'num_dependents_partner', 'paperless_and_echeck', 'tenure_to_charge_ratio',
    'is_senior_alone', 'service_to_charge_ratio'
]
print(f"Engineered {len(engineered_features)} features.")
df[engineered_features].head()

"""## 3. Encoding (Leakage-Safe)

Categorical variables are one-hot encoded and numeric variables are scaled, but this is done **inside a scikit-learn `Pipeline`/`ColumnTransformer`**, fit only on the training data. This is what "leakage-safe" means in practice: the test set never influences how encoding/scaling parameters are learned.

"""

# Drop identifier and raw target/leak columns from the feature set
drop_cols = ['customerID', 'Churn', 'Churn_binary']
X = df.drop(columns=drop_cols)
y = df['Churn_binary']

categorical_cols = X.select_dtypes(include=['object', 'category']).columns.tolist()
numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()

print(f"Categorical columns ({len(categorical_cols)}): {categorical_cols}")
print(f"Numeric columns ({len(numeric_cols)}): {numeric_cols}")

preprocessor = ColumnTransformer(transformers=[
    ('num', StandardScaler(), numeric_cols),
    ('cat', OneHotEncoder(handle_unknown='ignore', drop='if_binary'), categorical_cols)
])

"""## 4. Stratified Train / Validation / Test Split

Churn is imbalanced (26.54% positive class), so we stratify on `y` at every split. Split: **70% train / 15% validation / 15% test**. The test set is set aside now and not touched again until Section 8 (final evaluation).

"""

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, stratify=y, random_state=RANDOM_SEED
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=RANDOM_SEED
)

print(f"Train: {X_train.shape}, Churn rate: {y_train.mean():.4f}")
print(f"Val:   {X_val.shape}, Churn rate: {y_val.mean():.4f}")
print(f"Test:  {X_test.shape}, Churn rate: {y_test.mean():.4f}")

"""## 5. Baseline Models: Logistic Regression & XGBoost

Two models, two purposes:
- **Logistic Regression** — interpretable baseline; coefficients give directional relationships.
- **XGBoost** — nonlinear, boosted-tree model; captures interactions the logistic model can't.

Both are wrapped in the same `preprocessor` pipeline so encoding is handled identically and safely for each.

"""

logreg_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000, random_state=RANDOM_SEED, class_weight='balanced'))
])
logreg_pipeline.fit(X_train, y_train)

val_proba_lr = logreg_pipeline.predict_proba(X_val)[:, 1]
val_pred_lr = (val_proba_lr >= 0.5).astype(int)

print("Logistic Regression — Validation performance")
print(f"ROC-AUC: {roc_auc_score(y_val, val_proba_lr):.4f}")
print(classification_report(y_val, val_pred_lr, target_names=['No Churn', 'Churn']))

xgb_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', XGBClassifier(
        random_state=RANDOM_SEED,
        eval_metric='logloss',
        scale_pos_weight=(y_train == 0).sum() / (y_train == 1).sum()  # handle imbalance
    ))
])
xgb_pipeline.fit(X_train, y_train)

val_proba_xgb = xgb_pipeline.predict_proba(X_val)[:, 1]
val_pred_xgb = (val_proba_xgb >= 0.5).astype(int)

print("XGBoost (baseline) — Validation performance")
print(f"ROC-AUC: {roc_auc_score(y_val, val_proba_xgb):.4f}")
print(classification_report(y_val, val_pred_xgb, target_names=['No Churn', 'Churn']))

"""## 6. Model Comparison (Validation Set)

Compare both baselines on ROC-AUC, precision, recall and F1 — never on accuracy alone, since a model that just predicts "No Churn" for everyone would still score ~73% accuracy on this dataset.

"""

comparison_rows = []
for name, proba, pred in [
    ('Logistic Regression', val_proba_lr, val_pred_lr),
    ('XGBoost (baseline)', val_proba_xgb, val_pred_xgb),
]:
    comparison_rows.append({
        'Model': name,
        'ROC-AUC': roc_auc_score(y_val, proba),
        'Precision': precision_score(y_val, pred),
        'Recall': recall_score(y_val, pred),
        'F1': f1_score(y_val, pred)
    })

model_comparison_df = pd.DataFrame(comparison_rows)
model_comparison_df.to_csv(TABLES_PATH + "model_comparison.csv", index=False)
model_comparison_df

"""## 7. Hyperparameter Tuning & Cross-Validation (XGBoost)

We tune XGBoost — the stronger baseline candidate for capturing interactions — using `GridSearchCV` with 5-fold stratified cross-validation on the **training set only**. Scoring is ROC-AUC, since business prioritization depends on a well-ranked probability, not just a 0.5-threshold label.

"""

param_grid = {
    'classifier__n_estimators': [100, 200],
    'classifier__max_depth': [3, 5],
    'classifier__learning_rate': [0.05, 0.1],
    'classifier__subsample': [0.8, 1.0]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_SEED)

grid_search = GridSearchCV(
    xgb_pipeline, param_grid, scoring='roc_auc', cv=cv, n_jobs=-1, verbose=1
)
grid_search.fit(X_train, y_train)

print("Best CV ROC-AUC:", grid_search.best_score_)
print("Best params:", grid_search.best_params_)

best_model = grid_search.best_estimator_

"""## 8. Final Model Selection & Evaluation on the Untouched Test Set

`best_model` (tuned XGBoost) is evaluated **once** on the test set that has not influenced any training or tuning decision so far. This is the number you report as the model's true generalization performance.

"""

test_proba = best_model.predict_proba(X_test)[:, 1]
test_pred = (test_proba >= 0.5).astype(int)

print("FINAL MODEL — Test set performance")
print(f"ROC-AUC: {roc_auc_score(y_test, test_proba):.4f}")
print(classification_report(y_test, test_pred, target_names=['No Churn', 'Churn']))

cm = confusion_matrix(y_test, test_pred)
fig, ax = plt.subplots(figsize=(5, 4))
ConfusionMatrixDisplay(cm, display_labels=['No Churn', 'Churn']).plot(ax=ax, cmap='Blues')
plt.title('Confusion Matrix — Final Model (Test Set)')
plt.tight_layout()
plt.savefig(FIGURES_PATH + "confusion_matrix.png", dpi=150)
plt.show()

fpr, tpr, _ = roc_curve(y_test, test_proba)
plt.figure(figsize=(5, 4))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc_score(y_test, test_proba):.3f}")
plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
plt.xlabel('False Positive Rate'); plt.ylabel('True Positive Rate')
plt.title('ROC Curve — Final Model')
plt.legend()
plt.tight_layout()
plt.savefig(FIGURES_PATH + "roc_curve.png", dpi=150)
plt.show()

precision_vals, recall_vals, _ = precision_recall_curve(y_test, test_proba)
plt.figure(figsize=(5, 4))
plt.plot(recall_vals, precision_vals)
plt.xlabel('Recall'); plt.ylabel('Precision')
plt.title('Precision-Recall Curve — Final Model')
plt.tight_layout()
plt.savefig(FIGURES_PATH + "pr_curve.png", dpi=150)
plt.show()

# Save final model + preprocessing pipeline
joblib.dump(best_model, MODELS_PATH + "final_churn_model.joblib")
print(f"Model saved to {MODELS_PATH}final_churn_model.joblib")

"""## 9. Churn Probability Scoring for Every Customer

Rather than a binary Yes/No, we score **every customer** with a continuous `P(Churn)`. This continuous score is what powers prioritization later — the business doesn't need a label, it needs a ranking.

"""

X_full = X.copy()
full_proba = best_model.predict_proba(X_full)[:, 1]

risk_scores_df = pd.DataFrame({
    'customerID': customer_ids,
    'P_Churn': full_proba,
    'MonthlyCharges': df['MonthlyCharges'],
    'TotalCharges': df['TotalCharges'],
    'tenure': df['tenure'],
    'Contract': df['Contract']
})
risk_scores_df.to_csv(TABLES_PATH + "customer_risk_scores.csv", index=False)
risk_scores_df.sort_values('P_Churn', ascending=False).head(10)

"""## 10. SHAP Explainability

EDA tells you *which groups* have higher observed churn. SHAP tells you *which features actually drove the model's prediction* — globally, and for individual customers. This is what turns a "black box" score into something you can defend to a business stakeholder.

"""

# Transform features through the fitted preprocessor to get the exact matrix XGBoost saw
fitted_preprocessor = best_model.named_steps['preprocessor']
xgb_model = best_model.named_steps['classifier']

X_test_transformed = fitted_preprocessor.transform(X_test)
feature_names = fitted_preprocessor.get_feature_names_out()

explainer = shap.TreeExplainer(xgb_model)
shap_values = explainer.shap_values(X_test_transformed)

shap.summary_plot(shap_values, X_test_transformed, feature_names=feature_names, show=False)
plt.tight_layout()
plt.savefig(FIGURES_PATH + "shap_summary.png", dpi=150, bbox_inches='tight')
plt.show()

# Individual explanation example: the single highest-risk customer in the test set
highest_risk_idx = np.argmax(best_model.predict_proba(X_test)[:, 1])

shap.force_plot(
    explainer.expected_value,
    shap_values[highest_risk_idx],
    X_test_transformed[highest_risk_idx],
    feature_names=feature_names,
    matplotlib=True,
    show=False
)
plt.tight_layout()
plt.savefig(FIGURES_PATH + "shap_individual_example.png", dpi=150, bbox_inches='tight')
plt.show()

print("Business translation note: SHAP shows which features push this customer's prediction")
print("up or down. Treat these as retention-lever HYPOTHESES, not proven causal effects.")

"""## 11. Customer Value Proxy / CLV Framework — Explicit Assumptions

**The dataset does not contain gross margin, retention cost, or true future lifetime.** So this is a transparent, editable *value proxy*, not finance-grade CLV. Every assumption is defined in one place below so you can change it and re-run everything downstream.

**Assumptions (documented, saved to `data/external/`):**
- Expected remaining relationship duration by contract type: Month-to-month = 12 months, One year = 24 months, Two year = 36 months.
- Gross margin assumption: 40% of charges are margin (editable).

"""

# --- ASSUMPTIONS TABLE (edit these to match real business inputs when available) ---
assumptions = {
    "expected_remaining_months": {
        "Month-to-month": 12,
        "One year": 24,
        "Two year": 36
    },
    "gross_margin_pct": 0.40
}

with open(EXTERNAL_PATH + "clv_assumptions.json", "w") as f:
    json.dump(assumptions, f, indent=2)

df['expected_remaining_months'] = df['Contract'].map(assumptions['expected_remaining_months'])

# Value proxy = realized historical value (TotalCharges) + expected future value (MonthlyCharges x remaining months x margin)
df['future_value_proxy'] = (df['MonthlyCharges'] * df['expected_remaining_months']
                             * assumptions['gross_margin_pct'])
df['customer_value_proxy'] = df['TotalCharges'] + df['future_value_proxy']

print("Value proxy computed. Assumptions saved to:", EXTERNAL_PATH + "clv_assumptions.json")
df[['customerID', 'Contract', 'TotalCharges', 'future_value_proxy', 'customer_value_proxy']].head()

"""## 12. Risk × Value Customer Segmentation

Combine `P(Churn)` with the value proxy into four business segments:

| Segment | Risk | Value | Action |
|---|---|---|---|
| Protect / Save | High | High | Highest-priority personalized retention |
| Develop | High | Low/Medium | Low-cost or automated intervention |
| Maintain | Low | High | Loyalty/engagement, avoid unnecessary discounting |
| Low priority | Low | Low | Minimal retention spend, monitor |

"High" risk/value are defined relative to the median in this dataset — an editable, transparent threshold.

"""

df['P_Churn'] = full_proba

risk_threshold = df['P_Churn'].median()
value_threshold = df['customer_value_proxy'].median()

def assign_segment(row):
    high_risk = row['P_Churn'] >= risk_threshold
    high_value = row['customer_value_proxy'] >= value_threshold
    if high_risk and high_value:
        return 'Protect / Save'
    elif high_risk and not high_value:
        return 'Develop'
    elif not high_risk and high_value:
        return 'Maintain'
    else:
        return 'Low priority'

df['segment'] = df.apply(assign_segment, axis=1)

segment_summary = df.groupby('segment').agg(
    customers=('customerID', 'count'),
    avg_P_Churn=('P_Churn', 'mean'),
    avg_value_proxy=('customer_value_proxy', 'mean'),
    total_value_proxy=('customer_value_proxy', 'sum')
).reset_index().sort_values('total_value_proxy', ascending=False)

segment_summary.to_csv(TABLES_PATH + "segment_summary.csv", index=False)
segment_summary

plt.figure(figsize=(7, 6))
sample = df.sample(min(1500, len(df)), random_state=RANDOM_SEED)
sns.scatterplot(data=sample, x='P_Churn', y='customer_value_proxy', hue='segment', alpha=0.6)
plt.axvline(risk_threshold, linestyle='--', color='gray')
plt.axhline(value_threshold, linestyle='--', color='gray')
plt.title('Customer Risk x Value Segmentation')
plt.xlabel('P(Churn)')
plt.ylabel('Customer Value Proxy')
plt.tight_layout()
plt.savefig(FIGURES_PATH + "customer_risk_value_segments.png", dpi=150)
plt.show()

"""## 13. Revenue-at-Risk

`Expected Monthly Revenue at Risk = Σ(MonthlyCharges × P(Churn))`

This is gross exposure — the recurring revenue that's economically "in play" if nothing is done. Section 15 converts this into *recoverable* revenue after accounting for intervention effectiveness and cost.

"""

df['monthly_revenue_at_risk'] = df['MonthlyCharges'] * df['P_Churn']

total_revenue_at_risk = df['monthly_revenue_at_risk'].sum()
revenue_at_risk_by_segment = df.groupby('segment')['monthly_revenue_at_risk'].sum().sort_values(ascending=False)

print(f"Total Expected Monthly Revenue at Risk: ${total_revenue_at_risk:,.2f}")
print("\nBy segment:")
print(revenue_at_risk_by_segment)

revenue_at_risk_by_segment.to_csv(TABLES_PATH + "revenue_at_risk.csv")

"""## 14. Retention Prioritization & Intervention Design

Rule-based mapping from the report's intervention hypothesis table. Each high-risk customer gets a **primary intervention hypothesis** based on their strongest observed risk signal. These are hypotheses from observational data — flagged as such, not proven effects — and should be validated with pilots where possible.

"""

def assign_intervention(row):
    if row['P_Churn'] < risk_threshold:
        return 'Monitor only'
    if row['Contract'] == 'Month-to-month':
        return 'Contract conversion / loyalty incentive'
    if row['PaymentMethod'] == 'Electronic check':
        return 'Payment-method migration / friction reduction'
    if row['tenure'] <= 12:
        return 'Early-life onboarding / proactive support'
    if row['TechSupport'] == 'No' or row['OnlineSecurity'] == 'No':
        return 'Targeted support/security bundle'
    if row['InternetService'] == 'Fiber optic':
        return 'Service quality/value review before discounting'
    if row['monthly_charge_bucket'] in ['Medium-High', 'High']:
        return 'Value review / targeted pricing intervention'
    return 'General retention outreach'

df['intervention'] = df.apply(assign_intervention, axis=1)

intervention_summary = (df[df['P_Churn'] >= risk_threshold]
                         .groupby('intervention')
                         .agg(customers=('customerID', 'count'),
                              total_revenue_at_risk=('monthly_revenue_at_risk', 'sum'))
                         .sort_values('total_revenue_at_risk', ascending=False))
intervention_summary

"""## 15. Budget Allocation, Scenario Analysis & ROI

**Core economic framework:**
```
Expected Revenue Saved ≈ Customers Targeted x P(Churn) x Intervention Effectiveness x Recoverable Customer Value
Net Benefit = Expected Revenue Saved - Intervention Cost
ROI = (Expected Revenue Saved - Intervention Cost) / Intervention Cost
```

Every assumption below (cost per intervention, effectiveness by scenario) is a placeholder you should replace with real business numbers when available. Customers are ranked by expected net benefit per rupee/dollar spent and funded greedily until the budget runs out — this is the "optimization problem, not a blanket discount" framing from the report.

"""

# --- ASSUMPTIONS: cost per customer per intervention type (editable placeholders) ---
intervention_cost = {
    'Contract conversion / loyalty incentive': 30,
    'Payment-method migration / friction reduction': 10,
    'Early-life onboarding / proactive support': 20,
    'Targeted support/security bundle': 25,
    'Service quality/value review before discounting': 40,
    'Value review / targeted pricing intervention': 35,
    'General retention outreach': 15,
    'Monitor only': 0
}

# --- ASSUMPTIONS: intervention effectiveness by scenario (probability the intervention prevents churn) ---
effectiveness_scenarios = {
    'Conservative': 0.10,
    'Base case': 0.20,
    'Optimistic': 0.35
}

df['intervention_cost'] = df['intervention'].map(intervention_cost)

# Recoverable value if retained = 1 year of margin-adjusted future value (editable assumption)
df['recoverable_value'] = df['MonthlyCharges'] * 12 * assumptions['gross_margin_pct']

targetable = df[df['P_Churn'] >= risk_threshold].copy()
print(f"Targetable (high-risk) customers: {len(targetable)}")

def run_scenario(effectiveness, budget):
    pool = targetable.copy()
    pool['expected_saving'] = pool['P_Churn'] * effectiveness * pool['recoverable_value']
    pool['expected_net_benefit'] = pool['expected_saving'] - pool['intervention_cost']
    pool['benefit_per_dollar'] = pool['expected_net_benefit'] / pool['intervention_cost'].replace(0, np.nan)
    pool = pool.sort_values('benefit_per_dollar', ascending=False)

    pool['cumulative_cost'] = pool['intervention_cost'].cumsum()
    funded = pool[pool['cumulative_cost'] <= budget]

    revenue_saved = funded['expected_saving'].sum()
    cost = funded['intervention_cost'].sum()
    net_benefit = revenue_saved - cost
    roi = net_benefit / cost if cost > 0 else np.nan

    return {
        'customers_funded': len(funded),
        'expected_revenue_saved': revenue_saved,
        'intervention_cost': cost,
        'net_benefit': net_benefit,
        'roi': roi
    }

BUDGET_LEVELS = [10000, 25000, 50000, 100000]

scenario_rows = []
for scenario_name, eff in effectiveness_scenarios.items():
    for budget in BUDGET_LEVELS:
        result = run_scenario(eff, budget)
        scenario_rows.append({'scenario': scenario_name, 'budget': budget, **result})

scenario_df = pd.DataFrame(scenario_rows)
scenario_df.to_csv(TABLES_PATH + "retention_scenarios.csv", index=False)
scenario_df

# ROI summary table (base case, mid-size budget) for the executive-facing headline number
headline = scenario_df[(scenario_df['scenario'] == 'Base case') & (scenario_df['budget'] == 50000)]
print("Headline (Base case, $50,000 budget):")
print(headline.to_string(index=False))

scenario_df.to_csv(TABLES_PATH + "roi_analysis.csv", index=False)

plt.figure(figsize=(8, 5))
for scenario_name in effectiveness_scenarios:
    subset = scenario_df[scenario_df['scenario'] == scenario_name]
    plt.plot(subset['budget'], subset['expected_revenue_saved'], marker='o', label=scenario_name)
plt.xlabel('Retention Budget ($)')
plt.ylabel('Expected Revenue Saved ($)')
plt.title('Budget Sensitivity — Expected Revenue Saved by Scenario')
plt.legend()
plt.tight_layout()
plt.savefig(FIGURES_PATH + "budget_sensitivity.png", dpi=150)
plt.show()

"""## 16. Save Final Customer-Level Table

One master table per customer: risk score, value proxy, segment, revenue at risk, recommended intervention, and cost/benefit — this is the operational output the retention team would actually work from.

"""

final_customer_table = df[[
    'customerID', 'P_Churn', 'customer_value_proxy', 'segment',
    'monthly_revenue_at_risk', 'intervention', 'intervention_cost', 'recoverable_value'
]].sort_values('monthly_revenue_at_risk', ascending=False)

final_customer_table.to_csv(TABLES_PATH + "final_customer_priority_list.csv", index=False)
final_customer_table.head(15)

"""## 17. Business Recommendations

Fill this section in with your own numbers once the notebook has run end-to-end on the real dataset — for a CV/interview, being able to state 2–3 concrete, numbers-backed recommendations (e.g. *"prioritizing the top N 'Protect/Save' customers under a $50k budget yields an estimated ROI of X"*) is far stronger than describing the pipeline alone.

**Template:**
1. **Where to spend first:** the "Protect / Save" segment — high churn risk *and* high value — is the highest-priority group under any budget scenario tested.
2. **Highest-leverage lever:** month-to-month contract conversion consistently shows the largest gap in observed churn (42.71% vs 2.83% for two-year contracts), making it the top intervention hypothesis to pilot.
3. **Budget efficiency:** report the ROI at the budget level you tested and how ROI changes as budget scales.
4. **Caveat to state explicitly:** every CLV, cost and effectiveness number here is an assumption, not a measured value — recommend running an actual retention pilot to replace assumptions with real effectiveness data before scaling spend.

**Reminder on the analytical hierarchy used throughout:** EDA = observed association → Model = predictive contribution → SHAP = feature attribution → Segmentation/CLV/ROI = business layer built on explicit assumptions. None of these prove causality on their own; only a controlled pilot or experiment can.

"""